import { Depot, FamilyResponse, DistributionResponse } from './types';

export const INITIAL_DEPOTS: Depot[] = [
  {
    id: 'jijel-01',
    code: 'DZ-JIJ-01',
    name: 'مستودع إغاثة جيجل 01 - العوانة',
    description: 'المستودع الرئيسي للإغاثة لبلديات الساحل الغربي لولاية جيجل مجهز بغرف تبريد',
    wilaya: 'جيجل',
    municipality: 'العوانة',
    address: 'القاعة متعددة الرياضات، الطريق الوطني رقم 43',
    googleMapsUrl: 'https://maps.google.com/?q=36.7828,5.7667',
    phone: '034 50 12 88',
    manager: 'السيد أحمد بن شريف',
    status: 'ACTIVE',
    totalCapacityPercent: 68,
    occupancyPercentage: 68,
    lastUpdated: 'منذ 10 دقائق',
    location: {
      wilaya: 'جيجل',
      commune: 'العوانة',
      address: 'القاعة متعددة الرياضات، الطريق الوطني رقم 43',
      googleMapsUrl: 'https://maps.google.com/?q=36.7828,5.7667',
    },
    contactInfo: {
      managerName: 'السيد أحمد بن شريف',
      phone: '034 50 12 88',
      email: 'depot.jijel@humanitarian-aid.dz',
    },
    zones: [
      {
        id: 'Zone A',
        title: 'المنطقة أ - المواد الغذائية والطرود التموينية',
        category: 'FOOD',
        description: 'تفريغ المواد الغذائية والمشروبات والمياه وحليب الأطفال والأدوية',
        maxCapacity: 1500,
        currentUnits: 1100,
        temperatureControl: true,
      },
      {
        id: 'Zone B',
        title: 'المنطقة ب - الأفرشة والبطانيات والمفروشات',
        category: 'MATTRESSES',
        description: 'أفرشة إسفنجية، بطانيات شتوية، وسائد وأكياس نوم',
        maxCapacity: 1200,
        currentUnits: 600,
      },
      {
        id: 'Zone C',
        title: 'المنطقة ج - الأجهزة الكهرومنزلية والمعدات',
        category: 'APPLIANCES',
        description: 'ثلاجات، مدافئ، أفران، مولدات كهربائية ومضخات',
        maxCapacity: 200,
        currentUnits: 25,
      },
      {
        id: 'Zone D',
        title: 'المنطقة د - الأثاث والأرائك والخيام',
        category: 'FURNITURE',
        description: 'كنبات، صالونات، طاولات وكراسي',
        maxCapacity: 150,
        currentUnits: 20,
      },
    ],
    items: [
      {
        id: 'item-food-jij',
        name: 'طرود غذائية متكاملة',
        nameFr: 'Food Parcels',
        category: 'FOOD',
        currentStock: 800,
        targetNeed: 500,
        unit: 'طرد',
        assignedZone: 'Zone A',
        priority: 'LOW',
        status: 'FULFILLED',
      },
      {
        id: 'item-water-jij',
        name: 'مياه معدنية معبأة (حزم 6 قوارير)',
        nameFr: 'Mineral Water Packs',
        category: 'WATER',
        currentStock: 350,
        targetNeed: 1500,
        unit: 'حزمة',
        assignedZone: 'Zone A',
        priority: 'CRITICAL',
        status: 'OPEN',
      },
      {
        id: 'item-blankets-jij',
        name: 'أغطية وبطانيات صوفية',
        nameFr: 'Blankets',
        category: 'BLANKETS',
        currentStock: 200,
        targetNeed: 500,
        unit: 'بطانية',
        assignedZone: 'Zone B',
        priority: 'HIGH',
        status: 'OPEN',
      },
      {
        id: 'item-mattress-jij',
        name: 'أفرشة إسفنجية مفردة ومزدوجة',
        nameFr: 'Mattresses',
        category: 'MATTRESSES',
        currentStock: 400,
        targetNeed: 400,
        unit: 'فراش',
        assignedZone: 'Zone B',
        priority: 'LOW',
        status: 'FULFILLED',
      },
      {
        id: 'item-clothes-jij',
        name: 'ألبسة شتوية ومعاطف أطفال',
        nameFr: 'Winter Clothes',
        category: 'CLOTHES',
        currentStock: 120,
        targetNeed: 450,
        unit: 'طقم',
        assignedZone: 'Zone B',
        priority: 'HIGH',
        status: 'OPEN',
      },
      {
        id: 'item-sofas-jij',
        name: 'أرائك وكنبات صالون',
        nameFr: 'Sofas',
        category: 'FURNITURE',
        currentStock: 20,
        targetNeed: 100,
        unit: 'كنبة',
        assignedZone: 'Zone D',
        priority: 'HIGH',
        status: 'OPEN',
      },
      {
        id: 'item-fridges-jij',
        name: 'ثلاجات منزلية مدمجة',
        nameFr: 'Refrigerators',
        category: 'APPLIANCES',
        currentStock: 5,
        targetNeed: 30,
        unit: 'ثلاجة',
        assignedZone: 'Zone C',
        priority: 'CRITICAL',
        status: 'OPEN',
      },
      {
        id: 'item-med-jij',
        name: 'حقائب إسعافات وأدوية طوارئ',
        nameFr: 'First Aid Kits',
        category: 'MEDICAL',
        currentStock: 90,
        targetNeed: 100,
        unit: 'حقيبة',
        assignedZone: 'Zone A',
        priority: 'LOW',
        status: 'PARTIALLY_FULFILLED',
      },
    ],
    batches: [
      {
        id: 'BATCH-2026-ALG-001',
        depotId: 'jijel-01',
        itemId: 'item-food-jij',
        itemName: 'حليب معقم 1 لتر',
        quantity: 300,
        unit: 'علبة',
        expiryDate: '2026-09-22',
        receivedDate: '2026-09-15',
        zone: 'Zone A',
        status: 'expiring_soon',
      },
      {
        id: 'BATCH-2026-ALG-002',
        depotId: 'jijel-01',
        itemId: 'item-food-jij',
        itemName: 'دقيق سميد معبأ 25 كغ',
        quantity: 150,
        unit: 'كيس',
        expiryDate: '2027-01-10',
        receivedDate: '2026-09-10',
        zone: 'Zone A',
        status: 'good',
      },
      {
        id: 'BATCH-2026-ALG-003',
        depotId: 'jijel-01',
        itemId: 'item-food-jij',
        itemName: 'معلبات تونة وسردين',
        quantity: 500,
        unit: 'علبة',
        expiryDate: '2027-08-30',
        receivedDate: '2026-09-12',
        zone: 'Zone A',
        status: 'good',
      },
    ],
  },
  {
    id: 'mila-01',
    code: 'DZ-MIL-01',
    name: 'مستودع ميلة المركزي - زغار',
    description: 'المقر المتقدم لتوزيع المساعدات والطرود للمناطق المتضررة بولاية ميلة',
    wilaya: 'ميلة',
    municipality: 'ميلة',
    address: 'حي زغار، المستودع البلدي المركزي قرب الحماية المدنية',
    googleMapsUrl: 'https://maps.google.com/?q=36.4503,6.2644',
    phone: '031 47 33 21',
    manager: 'السيدة فتيحة مرزوق',
    status: 'ACTIVE',
    totalCapacityPercent: 84,
    occupancyPercentage: 84,
    lastUpdated: 'منذ 3 دقائق',
    location: {
      wilaya: 'ميلة',
      commune: 'ميلة',
      address: 'حي زغار، المستودع البلدي المركزي قرب الحماية المدنية',
      googleMapsUrl: 'https://maps.google.com/?q=36.4503,6.2644',
    },
    contactInfo: {
      managerName: 'السيدة فتيحة مرزوق',
      phone: '031 47 33 21',
      email: 'depot.mila@humanitarian-aid.dz',
    },
    zones: [
      {
        id: 'Zone A',
        title: 'المنطقة أ - المواد الغذائية والطرود',
        category: 'FOOD',
        description: 'تفريغ وتخزين الأغذية وحليب الأطفال',
        maxCapacity: 1200,
        currentUnits: 1100,
        temperatureControl: true,
      },
      {
        id: 'Zone B',
        title: 'المنطقة ب - المفروشات والأفرشة',
        category: 'MATTRESSES',
        description: 'بطانيات، أفرشة نوم، وسائد',
        maxCapacity: 900,
        currentUnits: 750,
      },
      {
        id: 'Zone C',
        title: 'المنطقة ج - الأجهزة الكهرومنزلية',
        category: 'APPLIANCES',
        description: 'ثلاجات، مدافئ، أفران، مضخات',
        maxCapacity: 150,
        currentUnits: 30,
      },
      {
        id: 'Zone D',
        title: 'المنطقة د - الأثاث والصالونات',
        category: 'FURNITURE',
        description: 'أرائك، طاولات، أسرة حديدية',
        maxCapacity: 100,
        currentUnits: 20,
      },
    ],
    items: [
      {
        id: 'item-food-mil',
        name: 'طرود غذائية متكاملة',
        nameFr: 'Food Parcels',
        category: 'FOOD',
        currentStock: 900,
        targetNeed: 600,
        unit: 'طرد',
        assignedZone: 'Zone A',
        priority: 'LOW',
        status: 'FULFILLED',
      },
      {
        id: 'item-water-mil',
        name: 'مياه شرب معبأة',
        nameFr: 'Mineral Water',
        category: 'WATER',
        currentStock: 800,
        targetNeed: 800,
        unit: 'حزمة',
        assignedZone: 'Zone A',
        priority: 'LOW',
        status: 'FULFILLED',
      },
      {
        id: 'item-blankets-mil',
        name: 'أغطية وبطانيات صوفية',
        nameFr: 'Blankets',
        category: 'BLANKETS',
        currentStock: 450,
        targetNeed: 500,
        unit: 'بطانية',
        assignedZone: 'Zone B',
        priority: 'LOW',
        status: 'PARTIALLY_FULFILLED',
      },
      {
        id: 'item-mattress-mil',
        name: 'أفرشة إسفنجية مفردة ومزدوجة',
        nameFr: 'Mattresses',
        category: 'MATTRESSES',
        currentStock: 150,
        targetNeed: 600,
        unit: 'فراش',
        assignedZone: 'Zone B',
        priority: 'CRITICAL',
        status: 'OPEN',
      },
      {
        id: 'item-sofas-mil',
        name: 'أرائك وكنبات صالون',
        nameFr: 'Sofas',
        category: 'FURNITURE',
        currentStock: 10,
        targetNeed: 80,
        unit: 'كنبة',
        assignedZone: 'Zone D',
        priority: 'CRITICAL',
        status: 'OPEN',
      },
      {
        id: 'item-fridges-mil',
        name: 'ثلاجات منزلية مدمجة',
        nameFr: 'Refrigerators',
        category: 'APPLIANCES',
        currentStock: 12,
        targetNeed: 40,
        unit: 'ثلاجة',
        assignedZone: 'Zone C',
        priority: 'HIGH',
        status: 'OPEN',
      },
      {
        id: 'item-heaters-mil',
        name: 'مدافئ غازية آمنة',
        nameFr: 'Gas Heaters',
        category: 'APPLIANCES',
        currentStock: 8,
        targetNeed: 60,
        unit: 'مدفأة',
        assignedZone: 'Zone C',
        priority: 'CRITICAL',
        status: 'OPEN',
      },
    ],
    batches: [
      {
        id: 'BATCH-2026-MIL-001',
        depotId: 'mila-01',
        itemId: 'item-food-mil',
        itemName: 'حليب أطفال رضع المرحلة 1',
        quantity: 200,
        unit: 'علبة',
        expiryDate: '2026-10-15',
        receivedDate: '2026-09-14',
        zone: 'Zone A',
        status: 'good',
      },
    ],
  },
  {
    id: 'skikda-01',
    code: 'DZ-SKI-01',
    name: 'مستودع سكيكدة - القل',
    description: 'مستودع دعم قوافل الإغاثة البحرية والبرية لبلديات غرب سكيكدة',
    wilaya: 'سكيكدة',
    municipality: 'القل',
    address: 'المنطقة الحرفية، مدخل مدينة القل',
    googleMapsUrl: 'https://maps.google.com/?q=37.0075,6.5683',
    phone: '038 71 45 10',
    manager: 'السيد رابح قسوم',
    status: 'ACTIVE',
    totalCapacityPercent: 42,
    occupancyPercentage: 42,
    lastUpdated: 'منذ 25 دقيقة',
    location: {
      wilaya: 'سكيكدة',
      commune: 'القل',
      address: 'المنطقة الحرفية، مدخل مدينة القل',
      googleMapsUrl: 'https://maps.google.com/?q=37.0075,6.5683',
    },
    contactInfo: {
      managerName: 'السيد رابح قسوم',
      phone: '038 71 45 10',
      email: 'depot.skikda@humanitarian-aid.dz',
    },
    zones: [
      {
        id: 'Zone A',
        title: 'المنطقة أ - المواد الغذائية',
        category: 'FOOD',
        description: 'طرود الأغذية والمياه',
        maxCapacity: 1000,
        currentUnits: 400,
      },
      {
        id: 'Zone B',
        title: 'المنطقة ب - المفروشات',
        category: 'MATTRESSES',
        description: 'بطانيات وأفرشة',
        maxCapacity: 800,
        currentUnits: 300,
      },
      {
        id: 'Zone C',
        title: 'المنطقة ج - الأجهزة والمعدات',
        category: 'APPLIANCES',
        description: 'أجهزة ومضخات',
        maxCapacity: 100,
        currentUnits: 15,
      },
      {
        id: 'Zone D',
        title: 'المنطقة د - الأثاث والخيام',
        category: 'FURNITURE',
        description: 'أثاث وكراسي',
        maxCapacity: 80,
        currentUnits: 10,
      },
    ],
    items: [
      {
        id: 'item-food-ski',
        name: 'طرود غذائية متكاملة',
        nameFr: 'Food Parcels',
        category: 'FOOD',
        currentStock: 350,
        targetNeed: 400,
        unit: 'طرد',
        assignedZone: 'Zone A',
        priority: 'LOW',
        status: 'PARTIALLY_FULFILLED',
      },
      {
        id: 'item-blankets-ski',
        name: 'أغطية وبطانيات صوفية',
        nameFr: 'Blankets',
        category: 'BLANKETS',
        currentStock: 250,
        targetNeed: 300,
        unit: 'بطانية',
        assignedZone: 'Zone B',
        priority: 'LOW',
        status: 'PARTIALLY_FULFILLED',
      },
      {
        id: 'item-mattress-ski',
        name: 'أفرشة إسفنجية مفردة ومزدوجة',
        nameFr: 'Mattresses',
        category: 'MATTRESSES',
        currentStock: 80,
        targetNeed: 350,
        unit: 'فراش',
        assignedZone: 'Zone B',
        priority: 'HIGH',
        status: 'OPEN',
      },
    ],
    batches: [],
  },
];

// Seed Families matching OpenAPI contract schemas
export const INITIAL_FAMILIES: FamilyResponse[] = [
  {
    id: 42,
    aidId: 'AID-DZ-2026-0042',
    headOfFamilyName: 'كريم المنصوري',
    phone: '+213 661 23 45 67',
    numberOfMembers: 5,
    wilaya: 'جيجل',
    commune: 'طاهير',
    location: 'مدرسة ابن خلدون الابتدائية، القسم 3',
    status: 'AFFECTED_DISPLACED',
    notes: 'عائلة متضررة من الفيضانات بحاجة عاجلة لحليب وأفرشة',
    totalDistributionsReceived: 2,
    pendingNeedsCount: 3,
    createdAt: '2026-09-19T07:15:00',
    updatedAt: '2026-09-19T08:50:00',
  },
  {
    id: 43,
    aidId: 'AID-DZ-2026-0043',
    headOfFamilyName: 'فاطمة الزهراء بوعكاز',
    phone: '+213 550 99 88 77',
    numberOfMembers: 4,
    wilaya: 'ميلة',
    commune: 'ميلة',
    location: 'مركز الإيواء المؤقت بالقاعة الرياضية زغار',
    status: 'SHELTERED',
    notes: 'أم مع 3 أطفال صغار، تم تسليم أفرشة وبطانيات',
    totalDistributionsReceived: 1,
    pendingNeedsCount: 1,
    createdAt: '2026-09-19T08:00:00',
    updatedAt: '2026-09-19T09:30:00',
  },
];

// Seed Distributions matching OpenAPI contract schemas
export const INITIAL_DISTRIBUTIONS: DistributionResponse[] = [
  {
    id: 501,
    familyId: 42,
    familyAidId: 'AID-DZ-2026-0042',
    headOfFamilyName: 'كريم المنصوري',
    depotId: 'jijel-01',
    depotName: 'مستودع إغاثة جيجل 01 - العوانة',
    category: 'BLANKETS',
    item: 'بطانيات صوفية شتوية عالية الكثافة',
    quantity: 5.0,
    unit: 'بطانية',
    distributedAt: '2026-09-19T10:00:00',
    notes: 'تم التسليم مباشرة لرب الأسرة مع التوقيع على الاستلام.',
  },
  {
    id: 502,
    familyId: 43,
    familyAidId: 'AID-DZ-2026-0043',
    headOfFamilyName: 'فاطمة الزهراء بوعكاز',
    depotId: 'mila-01',
    depotName: 'مستودع ميلة المركزي - زغار',
    category: 'MATTRESSES',
    item: 'أفرشة نوم إسفنجية سميكة',
    quantity: 4.0,
    unit: 'فراش',
    distributedAt: '2026-09-19T11:15:00',
    notes: 'تسليم مع طرد غذائي شهري متكامل.',
  },
];
