import { Depot } from './types';

export const INITIAL_DEPOTS: Depot[] = [
  {
    id: 'jijel-01',
    code: 'DZ-JIJ-01',
    name: 'مستودع إغاثة جيجل 01 - العوانة',
    wilaya: 'جيجل',
    municipality: 'العوانة',
    address: 'القاعة متعددة الرياضات، الطريق الوطني رقم 43',
    googleMapsUrl: 'https://maps.google.com/?q=36.7828,5.7667',
    phone: '034 50 12 88',
    manager: 'السيد أحمد بن شريف',
    status: 'urgent',
    totalCapacityPercent: 68,
    lastUpdated: 'منذ 10 دقائق',
    zones: [
      {
        id: 'Zone A',
        title: 'المنطقة أ - المواد الغذائية والطرود التموينية',
        category: 'food',
        description: 'تفريغ المواد الغذائية والمشروبات والمياه وحليب الأطفال',
        maxCapacity: 1500,
        currentUnits: 1100,
        temperatureControl: true,
      },
      {
        id: 'Zone B',
        title: 'المنطقة ب - الأفرشة والبطانيات والمفروشات',
        category: 'bedding',
        description: 'أفرشة إسفنجية، بطانيات شتوية، وسائد وأكياس نوم',
        maxCapacity: 1200,
        currentUnits: 600,
      },
      {
        id: 'Zone C',
        title: 'المنطقة ج - الأجهزة الكهرومنزلية والمعدات',
        category: 'appliances',
        description: 'ثلاجات، مدافئ، أفران، مولدات كهربائية ومضخات',
        maxCapacity: 200,
        currentUnits: 25,
      },
      {
        id: 'Zone D',
        title: 'المنطقة د - الأثاث والأرائك',
        category: 'furniture',
        description: 'كنبات، صالونات، طاولات وكراسي',
        maxCapacity: 150,
        currentUnits: 20,
      },
    ],
    items: [
      {
        id: 'item-food-jij',
        name: 'طرود غذائية متكاملة',
        nameFr: 'Food Parcels',
        category: 'food',
        currentStock: 800,
        targetNeed: 500,
        unit: 'طرد',
        assignedZone: 'Zone A',
        priority: 'low',
      },
      {
        id: 'item-blankets-jij',
        name: 'أغطية وبطانيات صوفية',
        nameFr: 'Blankets',
        category: 'bedding',
        currentStock: 200,
        targetNeed: 500,
        unit: 'بطانية',
        assignedZone: 'Zone B',
        priority: 'urgent',
      },
      {
        id: 'item-mattress-jij',
        name: 'أفرشة إسفنجية مفردة ومزدوجة',
        nameFr: 'Mattresses',
        category: 'bedding',
        currentStock: 400,
        targetNeed: 400,
        unit: 'فراش',
        assignedZone: 'Zone B',
        priority: 'low',
      },
      {
        id: 'item-sofas-jij',
        name: 'أرائك وكنبات صالون',
        nameFr: 'Sofas',
        category: 'furniture',
        currentStock: 20,
        targetNeed: 100,
        unit: 'كنبة',
        assignedZone: 'Zone D',
        priority: 'urgent',
      },
      {
        id: 'item-fridges-jij',
        name: 'ثلاجات منزلية مدمجة',
        nameFr: 'Refrigerators',
        category: 'appliances',
        currentStock: 5,
        targetNeed: 30,
        unit: 'ثلاجة',
        assignedZone: 'Zone C',
        priority: 'urgent',
      },
      {
        id: 'item-water-jij',
        name: 'مياه معدنية معبأة (حزم 6ق)',
        nameFr: 'Mineral Water',
        category: 'food',
        currentStock: 1200,
        targetNeed: 600,
        unit: 'حزمة',
        assignedZone: 'Zone A',
        priority: 'low',
      }
    ],
    batches: [
      {
        id: 'batch-001',
        depotId: 'jijel-01',
        itemId: 'item-milk-jij',
        itemName: 'حليب معقم كامل الدسم (علب 1 لتر)',
        quantity: 300,
        unit: 'علبة',
        expiryDate: '2026-09-22',
        receivedDate: '2026-09-15',
        zone: 'Zone A',
        status: 'expiring_soon',
      },
      {
        id: 'batch-002',
        depotId: 'jijel-01',
        itemId: 'item-food-jij',
        itemName: 'معلبات تونة وبقوليات جافة',
        quantity: 500,
        unit: 'علبة',
        expiryDate: '2027-04-10',
        receivedDate: '2026-09-17',
        zone: 'Zone A',
        status: 'good',
      },
      {
        id: 'batch-003',
        depotId: 'jijel-01',
        itemId: 'item-baby-jij',
        itemName: 'حليب أطفال رضع درجة 1',
        quantity: 120,
        unit: 'علبة',
        expiryDate: '2026-10-05',
        receivedDate: '2026-09-16',
        zone: 'Zone A',
        status: 'expiring_soon',
      }
    ]
  },
  {
    id: 'mila-01',
    code: 'DZ-MIL-01',
    name: 'مستودع إغاثة ميلة 01 - القرارم قوقة',
    wilaya: 'ميلة',
    municipality: 'القرارم قوقة',
    address: 'مستودع ديوان الحبوب، المنطقة الصناعية',
    googleMapsUrl: 'https://maps.google.com/?q=36.4503,6.2644',
    phone: '031 57 44 20',
    manager: 'السيدة فتيحة قادري',
    status: 'urgent',
    totalCapacityPercent: 54,
    lastUpdated: 'منذ 25 دقيقة',
    zones: [
      {
        id: 'Zone A',
        title: 'المنطقة أ - تموين غذائي',
        category: 'food',
        description: 'فرز المواد الغذائية والمياه ومواد الإفطار',
        maxCapacity: 2000,
        currentUnits: 1400,
        temperatureControl: true,
      },
      {
        id: 'Zone B',
        title: 'المنطقة ب - أفرشة وأغطية',
        category: 'bedding',
        description: 'الأفرشة الإسفنجية والأغطية الصوفية',
        maxCapacity: 1000,
        currentUnits: 800,
      },
      {
        id: 'Zone C',
        title: 'المنطقة ج - كهرومنزلي ومولدات',
        category: 'appliances',
        description: 'ثلاجات، أجهزة تسخين وأفران طبخ',
        maxCapacity: 250,
        currentUnits: 40,
      },
      {
        id: 'Zone D',
        title: 'المنطقة د - أثاث وكنبات',
        category: 'furniture',
        description: 'أثاث الصالون وتأثيث المنازل المتضررة',
        maxCapacity: 120,
        currentUnits: 15,
      },
    ],
    items: [
      {
        id: 'item-food-mil',
        name: 'طرود غذائية متكاملة',
        nameFr: 'Food Parcels',
        category: 'food',
        currentStock: 1200,
        targetNeed: 1500,
        unit: 'طرد',
        assignedZone: 'Zone A',
        priority: 'moderate',
      },
      {
        id: 'item-blankets-mil',
        name: 'أغطية وبطانيات شتوية',
        nameFr: 'Blankets',
        category: 'bedding',
        currentStock: 650,
        targetNeed: 600,
        unit: 'بطانية',
        assignedZone: 'Zone B',
        priority: 'low',
      },
      {
        id: 'item-mattress-mil',
        name: 'أفرشة نوم مريحة',
        nameFr: 'Mattresses',
        category: 'bedding',
        currentStock: 150,
        targetNeed: 500,
        unit: 'فراش',
        assignedZone: 'Zone B',
        priority: 'urgent',
      },
      {
        id: 'item-sofas-mil',
        name: 'أرائك وكنبات',
        nameFr: 'Sofas',
        category: 'furniture',
        currentStock: 10,
        targetNeed: 60,
        unit: 'كنبة',
        assignedZone: 'Zone D',
        priority: 'urgent',
      },
      {
        id: 'item-water-mil',
        name: 'مياه معدنية معبأة',
        nameFr: 'Bottled Water',
        category: 'food',
        currentStock: 3500,
        targetNeed: 2000,
        unit: 'حزمة',
        assignedZone: 'Zone A',
        priority: 'low',
      },
      {
        id: 'item-fridges-mil',
        name: 'ثلاجات منزلية',
        nameFr: 'Fridges',
        category: 'appliances',
        currentStock: 8,
        targetNeed: 25,
        unit: 'ثلاجة',
        assignedZone: 'Zone C',
        priority: 'urgent',
      }
    ],
    batches: [
      {
        id: 'batch-101',
        depotId: 'mila-01',
        itemId: 'item-milk-mil',
        itemName: 'ياغورت وأجبان طازجة',
        quantity: 450,
        unit: 'علبة',
        expiryDate: '2026-09-24',
        receivedDate: '2026-09-17',
        zone: 'Zone A',
        status: 'expiring_soon',
      }
    ]
  },
  {
    id: 'skikda-01',
    code: 'DZ-SKI-01',
    name: 'مستودع إغاثة سكيكدة 01 - القل',
    wilaya: 'سكيكدة',
    municipality: 'القل',
    address: 'مجمع التكوين المهني الشهيد زايدي',
    googleMapsUrl: 'https://maps.google.com/?q=37.0069,6.5622',
    phone: '038 72 19 05',
    manager: 'السيد كمال بوساحة',
    status: 'urgent',
    totalCapacityPercent: 42,
    lastUpdated: 'منذ 40 دقيقة',
    zones: [
      {
        id: 'Zone A',
        title: 'المنطقة أ - تموين غذائي',
        category: 'food',
        description: 'أغذية جافة ومعلبات',
        maxCapacity: 1200,
        currentUnits: 650,
      },
      {
        id: 'Zone B',
        title: 'المنطقة ب - أفرشة وأغطية',
        category: 'bedding',
        description: 'بطانيات وأفرشة',
        maxCapacity: 800,
        currentUnits: 250,
      },
      {
        id: 'Zone C',
        title: 'المنطقة ج - كهرومنزلي',
        category: 'appliances',
        description: 'أجهزة تبريد وتسخين',
        maxCapacity: 150,
        currentUnits: 12,
      },
      {
        id: 'Zone D',
        title: 'المنطقة د - أثاث متنوع',
        category: 'furniture',
        description: 'أثاث منزلي',
        maxCapacity: 100,
        currentUnits: 18,
      },
    ],
    items: [
      {
        id: 'item-blankets-ski',
        name: 'أغطية وبطانيات',
        nameFr: 'Blankets',
        category: 'bedding',
        currentStock: 100,
        targetNeed: 400,
        unit: 'بطانية',
        assignedZone: 'Zone B',
        priority: 'urgent',
      },
      {
        id: 'item-fridges-ski',
        name: 'ثلاجات مدمجة',
        nameFr: 'Fridges',
        category: 'appliances',
        currentStock: 2,
        targetNeed: 20,
        unit: 'ثلاجة',
        assignedZone: 'Zone C',
        priority: 'urgent',
      },
      {
        id: 'item-mattress-ski',
        name: 'أفرشة نوم',
        nameFr: 'Mattresses',
        category: 'bedding',
        currentStock: 150,
        targetNeed: 350,
        unit: 'فراش',
        assignedZone: 'Zone B',
        priority: 'urgent',
      },
      {
        id: 'item-food-ski',
        name: 'طرود غذائية',
        nameFr: 'Food Parcels',
        category: 'food',
        currentStock: 450,
        targetNeed: 400,
        unit: 'طرد',
        assignedZone: 'Zone A',
        priority: 'low',
      }
    ],
    batches: []
  }
];
